{"uuid": "df2cf543-8505-4be8-baa1-c0400243eb24", "children": ["f2989453-d56b-4567-a265-2302117a40d7"], "befores": [{"name": "login_user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input class=\"text input__textfield text_type_main-default\" name=\"name\" type=\"text\"> is not clickable at point (640,385) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Diplom_3\\conftest.py\", line 32, in login_user\n    login_page.fill_field_email(user.email)\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Diplom_3\\pages\\login_page.py\", line 24, in fill_field_email\n    self.fill_field(self.field_email, t_data)\n  File \"C:\\Diplom_3\\pages\\base_page.py\", line 41, in fill_field\n    self.find_element(el_xpath).click()\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "open page", "status": "passed", "start": 1730190958471, "stop": 1730190959722}, {"name": "wait button register", "status": "passed", "start": 1730190959722, "stop": 1730190959785}, {"name": "fill field name", "status": "passed", "parameters": [{"name": "t_data", "value": "'name20241029113558'"}], "start": 1730190959785, "stop": 1730190960408}, {"name": "fill field email", "status": "passed", "parameters": [{"name": "t_data", "value": "'FedorIdolenkov_20241029113558@ya.ya'"}], "start": 1730190960408, "stop": 1730190960998}, {"name": "fill field pass", "status": "passed", "parameters": [{"name": "t_data", "value": "'psswrd20241029113558'"}], "start": 1730190960998, "stop": 1730190961547}, {"name": "click button register", "status": "passed", "start": 1730190961547, "stop": 1730190961857}, {"name": "wait button login", "status": "passed", "start": 1730190961857, "stop": 1730190962394}, {"name": "open page", "status": "passed", "start": 1730190962394, "stop": 1730190962606}, {"name": "fill field email", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input class=\"text input__textfield text_type_main-default\" name=\"name\" type=\"text\"> is not clickable at point (640,385) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Diplom_3\\pages\\login_page.py\", line 24, in fill_field_email\n    self.fill_field(self.field_email, t_data)\n  File \"C:\\Diplom_3\\pages\\base_page.py\", line 41, in fill_field\n    self.find_element(el_xpath).click()\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Diplom_3\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "t_data", "value": "'FedorIdolenkov_20241029113558@ya.ya'"}], "start": 1730190962606, "stop": 1730190962927}], "start": 1730190958468, "stop": 1730190962927}], "start": 1730190958468, "stop": 1730190963000}